// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-NzvKlnkPpgINXOqs8z4MutSkgjcHwM',
    appId: '1:736930064403:web:7f466d127bd34deda2b7e6',
    messagingSenderId: '736930064403',
    projectId: 'appagenda-ca7f1',
    authDomain: 'appagenda-ca7f1.firebaseapp.com',
    storageBucket: 'appagenda-ca7f1.appspot.com',
    measurementId: 'G-Y5V4CGDPRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiN7HBvLq4tS3YTNw6t-SomCvVUfHUBUI',
    appId: '1:736930064403:android:27d2e0d1606bdd43a2b7e6',
    messagingSenderId: '736930064403',
    projectId: 'appagenda-ca7f1',
    storageBucket: 'appagenda-ca7f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-dNX42l49X62ZSt9kPlREGMgrPZITZI',
    appId: '1:736930064403:ios:df00546db4202fc9a2b7e6',
    messagingSenderId: '736930064403',
    projectId: 'appagenda-ca7f1',
    storageBucket: 'appagenda-ca7f1.appspot.com',
    iosClientId: '736930064403-8r5dnkaa6is3nothu2h6o22jjpao3eol.apps.googleusercontent.com',
    iosBundleId: 'br.com.otiliopaulo.appcapf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-dNX42l49X62ZSt9kPlREGMgrPZITZI',
    appId: '1:736930064403:ios:df00546db4202fc9a2b7e6',
    messagingSenderId: '736930064403',
    projectId: 'appagenda-ca7f1',
    storageBucket: 'appagenda-ca7f1.appspot.com',
    iosClientId: '736930064403-8r5dnkaa6is3nothu2h6o22jjpao3eol.apps.googleusercontent.com',
    iosBundleId: 'br.com.otiliopaulo.appcapf',
  );
}
